### ISSUE TITLE
When will the code be uploaded?

### ISSUE THREAD

**Issue by Zbnzbnzbn** [lapisrocks/fedselect#1]
I found this repository from the paper, but now there is only the readme.md.When will the code be uploaded?
Thank you for your time and consideration.

**Comment by OverAny** [comment]
@rishub-tamirisa, could you address this?

**Comment by rishub-tamirisa** [comment]
Hello @Zbnzbnzbn ! Thanks for reaching out. We plan to clean up and release the code this month. Apologies for the delay, I was busy with several other deadlines for the last few months.

**Comment by Jason7282** [comment]
@rishub-tamirisa Do you have any plans to upload the code recently? Thanks for your time and consideration.

**Comment by xiaoshen-212** [comment]
When do you plan to upload the code?Thanks for your time and consideration.

**Comment by xiaoshen-212** [comment]
@rishub-tamirisa

**Comment by yuhufeng** [comment]
@rishub-tamirisa I was wondering if you have any plans to release the code associated with this project. If there is a timeline or any information regarding the release, I would be grateful if you could share it. Thank you for your time and consideration.

**Comment by rishub-tamirisa** [comment]
Apologies, I got very delayed cleaning up the camera-ready code due to other projects. It's uploaded now.
